"""
Nexus AI — Blueprint / Architectural Metadata Endpoint
GET /api/blueprint — Returns the execution flow (Mermaid) and term dictionary.
"""
from fastapi import APIRouter

router = APIRouter(prefix="/api", tags=["architecture"])


@router.get("/blueprint")
def get_blueprint():
    """Returns structured architectural metadata for the Nexus AI pipeline."""
    return {
        "execution_flow": (
            "graph TD\n"
            "  step1[Classify] --> step2[Triage]\n"
            "  step2 --> step3[RAG Retrieval]\n"
            "  step3 --> step4[Ranking]\n"
            "  step4 --> step5[Resolution]\n"
            "  step5 --> step6[Judge]\n"
            "  step6 --> step7[Automation]"
        ),
        "dictionary": [
            {
                "term": "category",
                "storage": "feedback.db",
                "nodeId": "step1",
                "description": "The primary classification category assigned to the ticket."
            },
            {
                "term": "confidence",
                "storage": "feedback.db",
                "nodeId": "step1",
                "description": "Confidence score generated by the TicketClassifier."
            },
            {
                "term": "priority",
                "storage": "ChromaDB",
                "nodeId": "step2",
                "description": "Priority level determined during the Triage phase."
            },
            {
                "term": "department",
                "storage": "ChromaDB",
                "nodeId": "step2",
                "description": "Departmental routing metadata for retrieved context."
            },
            {
                "term": "embedded document content",
                "storage": "ChromaDB",
                "nodeId": "step3",
                "description": "Vector-embedded knowledge base content used for RAG."
            },
            {
                "term": "resolution_steps",
                "storage": "feedback.db",
                "nodeId": "step5",
                "description": "Detailed reasoning and steps produced by the ResolutionAgent."
            },
            {
                "term": "judge_scores",
                "storage": "feedback.db",
                "nodeId": "step6",
                "description": "Quality and safety evaluation scores from the LLM Judge."
            },
            {
                "term": "agent_action",
                "storage": "feedback.db",
                "nodeId": "step7",
                "description": "The final outcome or tool execution triggered by the pipeline."
            }
        ],
        "dependencies": [
            {"from": "api/routes/pipeline.py", "to": "core/classifier.py", "type": "import"},
            {"from": "api/routes/pipeline.py", "to": "core/agent.py", "type": "import"},
            {"from": "api/routes/pipeline.py", "to": "core/rag.py", "type": "import"},
            {"from": "api/routes/pipeline.py", "to": "core/judge.py", "type": "import"}
        ]
    }
